trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/webapp/*
    - src/setup.py
    - changelog.md

variables:
  - name: tag
    value: $(Build.BuildId)
  - name: container_repository
    value: klantenservice-chat-kennisbank
  - name: app_name
    value: klantenservice-chat-kennisbank
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: kvName
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: kv-ml-pltfrm-prd
    ${{ else }}:
      value: kv-ml-pltfrm-dev
  - name: serviceConnection
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: Pitwall-Prod
    ${{ else }}:
      value: Pitwall-Dev
  - name: resourceGroup
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: rg-datapltfrm-prd
    ${{ else }}:
      value: rg-datapltfrm-dev
stages:

- stage: CI  
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: lint
    displayName: lint checks
    steps:
    - checkout: self
    - script: pip install pre-commit==3.8.0
    - bash: chmod +x scripts/lint
    - bash: ./scripts/lint
  - job: SastBandit
    displayName: Static application security testing with Bandit
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
    - script: |
        python -m pip install bandit
      name: install_bandit
      displayName: 'Install bandit'
    # bandit -lll means only flag HIGH severity issues
    - script: |
        python -m bandit -r ./src -lll
      displayName: 'Bandit scan'
      condition: succeeded() 
  - job: SastMdso
    displayName: Static application security testing with Terrascan and Trivy
    steps:
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps'
      inputs:
        tools: 'terrascan, trivy'
        break: true # this build step if any high severity level results are found.
        publish: true # will publish the output SARIF results file to the chosen pipeline artifact
  - job: test
    displayName: tests
    steps:
    - bash: echo TO BE ADDED

- stage: DeployTest
  dependsOn: CI
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeployWebAppTest
    displayName: deploy Web App on Test deployment slot 
    environment: 
      name: Test
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: keyvault-firewall.yaml
            parameters:
              serviceConnection: $(serviceConnection)
              kvName: $(kvName)
              resourceGroup: $(resourceGroup)

          - task: Docker@2
            displayName: Build docker image for test deployment slot web app
            inputs:
              command: build
              containerRegistry: Pitwall-datapltfrm-docker-prd
              repository: $(container_repository)
              dockerfile: ./Dockerfile.app
              buildContext: $(Build.SourcesDirectory)
              tags: $(tag)-tst
              arguments: '--build-arg ENVIRONMENT="tst" --build-arg BUILD_TAG=$(tag)'

          - task: Docker@2
            displayName: Push docker image for test deployment slot web app
            inputs:
              command: push
              containerRegistry: Pitwall-datapltfrm-docker-prd
              repository: $(container_repository)
              dockerfile: ./Dockerfile.app
              buildContext: $(Build.SourcesDirectory)
              tags: $(tag)-tst

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy Web App Test Slot
            inputs:
              ConnectionType: AzureRM
              azureSubscription: Pitwall-Prod
              appType: webAppContainer
              WebAppName: $(app_name)
              deployToSlotOrASE: true
              resourceGroupName: rg-mlcontainers-prd
              slotName: tst
              DockerNamespace: crmlpltfrmprd.azurecr.io
              DockerRepository: $(container_repository)
              DockerImageTag: $(tag)-tst
              TakeAppOfflineFlag: true
              AppSettings: |
                -OPENAI_API_KEY "$(OPENAI-API-KEY)" -OPENAI_ENDPOINT "$(OPENAI-ENDPOINT)" -OPENAI_SWEDEN_ENDPOINT "$(OPENAI-SWEDEN-ENDPOINT)" -OPENAI_SWEDEN "$(OPENAI-SWEDEN)" -APPLICATION_INSIGHTS_CONNECTION_STRING "$(APPLICATION-INSIGHTS-CONNECTION-STRING)" -TEAMS_WEBHOOK_CHATBOT_ALLY_FEEDBACK "$(TEAMS-WEBHOOK-CHATBOT-ALLY-FEEDBACK)" -TEAMS_WEBHOOK_DATASCIENCE_ALGEMEEN "$(TEAMS-WEBHOOK-DATASCIENCE-ALGEMEEN)"  -DATALAKE_NAME "$(DATALAKE-NAME)" -DATALAKE_NAME_PRD "$(DATALAKE-NAME-PRD)" -DATALAKE_NAME_DEV "$(DATALAKE-NAME-DEV)"

- stage: DeployAcc
  dependsOn: CI
  condition: succeeded()
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeployWebAppAcc
    displayName: deploy Web App on Acceptance deployment slot 
    environment: 
      name: Acc
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: keyvault-firewall.yaml
            parameters:
              serviceConnection: $(serviceConnection)
              kvName: $(kvName)
              resourceGroup: $(resourceGroup)

          - task: Docker@2
            displayName: Build docker image for acc deployment slot web app
            inputs:
              command: build
              containerRegistry: Pitwall-datapltfrm-docker-prd
              repository: $(container_repository)
              dockerfile: ./Dockerfile.app
              buildContext: $(Build.SourcesDirectory)
              tags: $(tag)-acc
              arguments: '--build-arg ENVIRONMENT="acc" --build-arg BUILD_TAG=$(tag)'

          - task: Docker@2
            displayName: Push docker image for acc deployment slot web app
            inputs:
              command: push
              containerRegistry: Pitwall-datapltfrm-docker-prd
              repository: $(container_repository)
              dockerfile: ./Dockerfile.app
              buildContext: $(Build.SourcesDirectory)
              tags: $(tag)-acc

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy Web App Test Slot
            inputs:
              ConnectionType: AzureRM
              azureSubscription: Pitwall-Prod
              appType: webAppContainer
              WebAppName: $(app_name)
              deployToSlotOrASE: true
              resourceGroupName: rg-mlcontainers-prd
              slotName: acc
              DockerNamespace: crmlpltfrmprd.azurecr.io
              DockerRepository: $(container_repository)
              DockerImageTag: $(tag)-acc
              TakeAppOfflineFlag: true
              AppSettings: |
                -OPENAI_API_KEY "$(OPENAI-API-KEY)" -OPENAI_ENDPOINT "$(OPENAI-ENDPOINT)" -OPENAI_SWEDEN_ENDPOINT "$(OPENAI-SWEDEN-ENDPOINT)" -OPENAI_SWEDEN "$(OPENAI-SWEDEN)" -APPLICATION_INSIGHTS_CONNECTION_STRING "$(APPLICATION-INSIGHTS-CONNECTION-STRING)" -TEAMS_WEBHOOK_CHATBOT_ALLY_FEEDBACK "$(TEAMS-WEBHOOK-CHATBOT-ALLY-FEEDBACK)" -TEAMS_WEBHOOK_DATASCIENCE_ALGEMEEN "$(TEAMS-WEBHOOK-DATASCIENCE-ALGEMEEN)"  -DATALAKE_NAME "$(DATALAKE-NAME)" -DATALAKE_NAME_PRD "$(DATALAKE-NAME-PRD)" -DATALAKE_NAME_DEV "$(DATALAKE-NAME-DEV)"

- stage: DeployStg
  dependsOn:  DeployAcc
  condition: and(succeeded(), eq(variables.isMain, true))
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeployWebAppPrdStg
    displayName: deploy Web App on Test Prod-staging slot 
    environment: 
      name: Productie&Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: keyvault-firewall.yaml
            parameters:
              serviceConnection: $(serviceConnection)
              kvName: $(kvName)
              resourceGroup: $(resourceGroup)
          - task: Docker@2
            displayName: Build docker image for production-staging deployment slot web app
            inputs:
              command: build
              containerRegistry: Pitwall-datapltfrm-docker-prd
              repository: $(container_repository)
              dockerfile: ./Dockerfile.app
              buildContext: $(Build.SourcesDirectory)
              tags: $(tag)-prd
              arguments: '--build-arg ENVIRONMENT="prd" --build-arg BUILD_TAG=$(tag)'

          - task: Docker@2
            displayName: Push docker image for prd-staging deployment slot web app
            inputs:
              command: push
              containerRegistry: Pitwall-datapltfrm-docker-prd
              repository: $(container_repository)
              dockerfile: ./Dockerfile.app
              buildContext: $(Build.SourcesDirectory)
              tags: $(tag)-prd

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy Web App Test Slot
            inputs:
              ConnectionType: AzureRM
              azureSubscription: Pitwall-Prod
              appType: webAppContainer
              WebAppName: $(app_name)
              deployToSlotOrASE: true
              resourceGroupName: rg-mlcontainers-prd
              slotName: stg
              DockerNamespace: crmlpltfrmprd.azurecr.io
              DockerRepository: $(container_repository)
              DockerImageTag: $(tag)-prd
              TakeAppOfflineFlag: true
              AppSettings: |
                -OPENAI_API_KEY "$(OPENAI-API-KEY)" -OPENAI_ENDPOINT "$(OPENAI-ENDPOINT)" -OPENAI_SWEDEN_ENDPOINT "$(OPENAI-SWEDEN-ENDPOINT)" -OPENAI_SWEDEN "$(OPENAI-SWEDEN)" -APPLICATION_INSIGHTS_CONNECTION_STRING "$(APPLICATION-INSIGHTS-CONNECTION-STRING)" -TEAMS_WEBHOOK_CHATBOT_ALLY_FEEDBACK "$(TEAMS-WEBHOOK-CHATBOT-ALLY-FEEDBACK)" -TEAMS_WEBHOOK_DATASCIENCE_ALGEMEEN "$(TEAMS-WEBHOOK-DATASCIENCE-ALGEMEEN)" -DATALAKE_NAME "$(DATALAKE-NAME)" -DATALAKE_NAME_PRD "$(DATALAKE-NAME-PRD)" -DATALAKE_NAME_DEV "$(DATALAKE-NAME-DEV)"
