trigger:
- none

schedules:
- cron: '0 20 * * MON-FRI'
  displayName: run daily 
  branches:
    include:
    - main
  always: true

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    - name: imageNameFaiss
      value: klantenservice-chat-kennisbank-faiss-generator-prd
    - name: imageNameReporting
      value: klantenservice-chat-kennisbank-reporting-prd
    - name:  containerInstanceNameFaiss
      value: ci-klantenservice-chat-kennisbank-faiss-generator-prd
    - name:  containerInstanceNameReporting
      value: ci-klantenservice-chat-kennisbank-reporting-prd
    - name: containerResourceGroup
      value: rg-mlcontainers-prd
    - name:  containerRegistry
      value: crmlpltfrmprd
    - name: kvName
      value: kv-ml-pltfrm-prd
    - name: serviceConnection
      value: Pitwall-Prod
    - name: resourceGroup
      value: rg-datapltfrm-prd
  - ${{ else }}:
    - name: imageNameFaiss
      value: klantenservice-chat-kennisbank-faiss-generator-dev
    - name: imageNameReporting
      value: klantenservice-chat-kennisbank-reporting-dev
    - name:  containerInstanceNameFaiss
      value: ci-klantenservice-chat-kennisbank-faiss-generator-dev
    - name:  containerInstanceNameReporting
      value: ci-klantenservice-chat-kennisbank-reporting-dev
    - name: containerResourceGroup
      value: rg-mlcontainers-dev
    - name:  containerRegistry
      value: crmlpltfrmdev
    - name: kvName
      value: kv-ml-pltfrm-dev
    - name: serviceConnection
      value: Pitwall-Dev
    - name: resourceGroup
      value: rg-datapltfrm-dev

stages:
- stage: RunContainers
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: RunContainers
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: Whitelist IP in KV
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |
          agent_ip=$(curl -s ifconfig.me)
          echo The IP address is $agent_ip
          echo "##vso[task.setvariable variable=agentIP]$agent_ip"
          az keyvault network-rule add --name $(kvName) --resource-group $(resourceGroup) --ip-address $agent_ip

          echo "Checking once per minute for up to 30 minutes if the IP has been whitelisted"
          for i in {1..30}; do
            ip_list=$(az keyvault show --name $(kvName) --query "properties.networkAcls.ipRules[].value" -o tsv)
            if echo "$ip_list" | grep -E "^$agent_ip"; then
              echo "IP address $agent_ip has been whitelisted successfully."
              break
            else
              echo "IP address $agent_ip has not been found in the whitelist. Waiting for 1 minute and checking again..."
              sleep 60
            fi
          done
    - script: |
        secret_names=$(paste -sd, "$(System.DefaultWorkingDirectory)/needed_secrets.txt")
        echo "##vso[task.setvariable variable=secretsList]$secret_names"
        echo "$secret_names"
      displayName: Read names of secrets from .txt

    - task: AzureKeyVault@2
      displayName: 'Access KV and get secrets'
      inputs:
        azureSubscription: $(serviceConnection)
        KeyVaultName: $(kvName)
        SecretsFilter: $(secretsList)

    - task: AzureCLI@2
      displayName: Remove whitelisted IP
      condition: always()
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |
          az keyvault network-rule remove --name $(kvName) --resource-group $(resourceGroup) --ip-address $(agentIP)

    - task: AzureCLI@2
      displayName: Delete old container instances
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |
          az container delete --name $(containerInstanceNameFaiss) --resource-group $(containerResourceGroup) --yes
          az container delete --name $(containerInstanceNameReporting) --resource-group $(containerResourceGroup) --yes

    - task: AzureCLI@2
      displayName: Run container instances
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |      
          az container create \
            --resource-group $(containerResourceGroup) \
            --name $(containerInstanceNameReporting) \
            --image $(containerRegistry).azurecr.io/$(imageNameReporting):latest \
            --assign-identity $(ID-UAMI-DATASCIENCE-CI-RESOURCE-ID) \
            --registry-username $(containerRegistry) \
            --registry-password $(CONTAINER-REGISTRY-PASSWORD) \
            --secure-environment-variables \
                TEAMS_WEBHOOK_DCC_KLANTENSERVICE_ALLY='$(TEAMS-WEBHOOK-DCC-KLANTENSERVICE-ALLY)' \
                TEAMS_WEBHOOK_DATASCIENCE_ALGEMEEN='$(TEAMS-WEBHOOK-DATASCIENCE-ALGEMEEN)' \
                SHAREPOINT_CLIENT_ID='$(SHAREPOINT-TEST-PYTHON-CLIENT-ID)' \
                SHAREPOINT_CLIENT_SECRET='$(SHAREPOINT-TEST-PYTHON-CLIENT-SECRET)' \
                AZURE_CLIENT_ID='$(ID-UAMI-DATASCIENCE-CI-CLIENT-ID)' \
                APPLICATION_INSIGHTS_CONNECTION_STRING='$(APPLICATION-INSIGHTS-CONNECTION-STRING)' \
                SHAREPOINT_URL='$(SHAREPOINT-URL)' \
                STORAGE_ACCOUNT='$(STORAGE-ACCOUNT)' \
                STORAGE_ACCOUNT_DEV='$(STORAGE-ACCOUNT-DEV)' \
                KLANTENSERVICE_CHAT_REPORTING_MENTION_USERS='$(KLANTENSERVICE-CHAT-REPORTING-MENTION-USERS)' \
                DATALAKE_NAME_DEV='$(DATALAKE-NAME-DEV)' \
                DATALAKE_NAME_PRD='$(DATALAKE-NAME-PRD)' \
                TENANT_ID='$(TENANT-ID)' \
                SPO_APPONLY_CERT_DCC_PYTHON_CLIENT_ID='$(SPO-APPONLY-CERT-DCC-PYTHON-CLIENT-ID)' \
                SPO_APPONLY_CERT_DCC_PYTHON_PRIVATE_KEY='$(SPO-APPONLY-CERT-DCC-PYTHON-PRIVATE-KEY)' \
                SPO_APPONLY_CERT_DCC_PYTHON_PRIVATE_KEY_THUMBPRINT='$(SPO-APPONLY-CERT-DCC-PYTHON-PRIVATE-KEY-THUMBPRINT)' \
            --restart-policy Never \
            --cpu 2 \
            --memory 8 \
            --os-type Linux
         
          az container create \
            --resource-group $(containerResourceGroup) \
            --name $(containerInstanceNameFaiss) \
            --image $(containerRegistry).azurecr.io/$(imageNameFaiss):latest \
            --assign-identity $(ID-UAMI-DATASCIENCE-CI-RESOURCE-ID) \
            --registry-username $(containerRegistry) \
            --registry-password $(CONTAINER-REGISTRY-PASSWORD) \
            --secure-environment-variables \
                OPENAI_API_KEY='$(OPENAI-API-KEY)' \
                OPENAI_ENDPOINT='$(OPENAI-ENDPOINT)' \
                AZURE_CLIENT_ID='$(ID-UAMI-DATASCIENCE-CI-CLIENT-ID)' \
                APPLICATION_INSIGHTS_CONNECTION_STRING='$(APPLICATION-INSIGHTS-CONNECTION-STRING)' \
                HELPJUICE_API_KEY='$(HELPJUICE-API-KEY)' \
                HELPJUICE_API_URL='$(HELPJUICE-API-URL)' \
                SHAREPOINT_URL='$(SHAREPOINT-URL)' \
                STORAGE_ACCOUNT='$(STORAGE-ACCOUNT)' \
                STORAGE_ACCOUNT_DEV='$(STORAGE-ACCOUNT-DEV)' \
                DATALAKE_NAME_DEV='$(DATALAKE-NAME-DEV)' \
                DATALAKE_NAME_PRD='$(DATALAKE-NAME-PRD)' \
            --restart-policy Never \
            --cpu 2 \
            --memory 8 \
            --os-type Linux
