FROM python:3.10-slim

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install --no-install-recommends dialog -y
RUN rm -rf /var/lib/apt/lists/*

ARG ENVIRONMENT="dev"
ENV ENVIRONMENT=${ENVIRONMENT}

WORKDIR /app
COPY requirements-faiss.txt requirements.txt 
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip3 install -e .

CMD ["python", "src/scheduled_runs/my_faiss/generate_faiss_index.py"]